function out = model
%
% submarine_cable_05_bonding_inductive.m
%
% Model exported on May 26 2025, 21:25 by COMSOL 6.2.0.339.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/Applications/COMSOL62/Multiphysics/applications/ACDC_Module/Tutorials,_Cables');

model.modelNode.create('comp1', true);

model.geom.create('geom1', 2);
model.geom('geom1').model('comp1');

model.mesh.create('mesh1', 'geom1');

model.physics.create('mf', 'InductionCurrents', 'geom1');
model.physics('mf').model('comp1');

model.study.create('std1');
model.study('std1').create('freq', 'Frequency');
model.study('std1').feature('freq').setSolveFor('/physics/mf', true);

model.param.label('Geometric Parameters 1');

% To import content from file, use:
% model.param.loadFile('FILENAME');
model.param.set('Dcon', '26.2[mm]', 'Diameter of main conductors (phase)');
model.param.set('Tins', '24.0[mm]', 'Insulation thickness (XLPE)');
model.param.set('Dins', '77.6[mm]', 'Diameter over insulation (XLPE and SCC)');
model.param.set('Tscc', '(Dins/2-Dcon/2-Tins)/2', 'Semi-conductive compound thickness');
model.param.set('Tpbs', '2.9[mm]', 'Lead sheath thickness');
model.param.set('Tpe', '2.9[mm]', 'Polyethylene sheath thickness');
model.param.set('Dpha', 'Dins+2*Tpbs+2*Tpe', 'Diameter over phase (including sheath and PE)');
model.param.set('Dpha3', 'Dpha*(2/sqrt(3)+1)', 'Diameter over three phases combined');
model.param.set('Dfic', '2.5[mm]', 'Diameter of fiber optic core');
model.param.set('Tfih', '0.5[mm]', 'Steel helix thickness (fiber)');
model.param.set('Dfib', '9.2[mm]', 'Diameter over fiber optic cable');
model.param.set('Dcab', '219.0[mm]', 'Outer diameter of submarine cable');
model.param.set('Darm', '(Dcab+Dpha3)/2', 'Central diameter of armor ring');
model.param.set('Tarm', '5.6[mm]', 'Armor thickness (wire diameter)');
model.param.set('Narm', '110', 'Number of armor wires in ring');
model.param.set('mfil', '0.5[mm]', 'Filler margin');
model.param.set('marm', 'pi*Darm/Narm-Tarm', 'Armor margin');
model.param.create('par2');
model.param('par2').label('Geometric Parameters 2');

% To import content from file, use:
% model.param('par2').loadFile('FILENAME');
model.param('par2').set('Acon', '500[mm^2]', 'Cross sectional area of main conductors (per phase)');
model.param('par2').set('Ncon', 'Acon/(pi*(Dcon/2)^2)', 'Conductor packing density (phase)');
model.param('par2').set('Apbs', 'pi*(Dins+Tpbs)*Tpbs', 'Cross sectional area of lead sheath (per phase)');
model.param('par2').set('Lsec1', '1/3', 'Relative length cross bonding section 1');
model.param('par2').set('Lsec2', '1-Lsec1-Lsec3', 'Relative length cross bonding section 2');
model.param('par2').set('Lsec3', '1/3', 'Relative length cross bonding section 3');
model.param('par2').set('Lcab', '10[km]', 'Total length of submarine cable');
model.param('par2').set('Scab', '1e5', 'Geometric scale factor (2Daxi model)');
model.param('par2').set('Lsec1', '1');
model.param('par2').set('Lsec3', '0');
model.param.create('par3');
model.param('par3').label('Electromagnetic Parameters');

% To import content from file, use:
% model.param('par3').loadFile('FILENAME');
model.param('par3').set('f0', '50[Hz]', 'Operating frequency');
model.param('par3').set('w0', '(2*pi*f0[1/Hz])[rad/s]', 'Angular frequency');
model.param('par3').set('V0', '220[kV]/sqrt(3)', 'Phase to ground voltage (amplitude)');
model.param('par3').set('I0', '655[A]*sqrt(2)', 'Rated current (amplitude)');
model.param('par3').set('Scup', '5.96e7[S/m]', ['Copper conductivity, at 20' native2unicode(hex2dec({'00' 'b0'}), 'unicode') 'C']);
model.param('par3').set('Spbs', '4.55e6[S/m]', ['Lead sheath conductivity, at 20' native2unicode(hex2dec({'00' 'b0'}), 'unicode') 'C']);
model.param('par3').set('Sarm', '4.03e6[S/m]', ['Armor wire conductivity, at 20' native2unicode(hex2dec({'00' 'b0'}), 'unicode') 'C']);
model.param('par3').set('Mcup', '1', 'Relative permeability, copper');
model.param('par3').set('Mpbs', '1', 'Relative permeability, lead sheath');
model.param('par3').set('Marm', '100-50*j', 'Relative permeability, armor wires');
model.param('par3').set('Dscup', 'min(1/real(sqrt(j*w0*mu0_const*Mcup*Scup)),Dcon/3)', 'Skin depth, copper (analytic)');
model.param('par3').set('Dspbs', 'min(1/real(sqrt(j*w0*mu0_const*Mpbs*Spbs)),12*Tpbs)', 'Skin depth, lead sheath (analytic)');
model.param('par3').set('Dsarm', 'min(1/real(sqrt(j*w0*mu0_const*Marm*Sarm)),Tarm/2)', 'Skin depth, armor wires (analytic)');
model.param('par3').set('Rcon', '1/Acon/Scup', ['Main conductor DC resistance per phase, at 20' native2unicode(hex2dec({'00' 'b0'}), 'unicode') 'C (analytic)']);
model.param('par3').set('Rpbs', '1/Apbs/Spbs', ['Lead sheath DC resistance per phase, at 20' native2unicode(hex2dec({'00' 'b0'}), 'unicode') 'C (analytic)']);
model.param('par3').set('Exlpe', '2.5', 'Relative permittivity XLPE (from IEC 60287)');
model.param('par3').set('Cpha', '2*pi*epsilon0_const*Exlpe/log((Dins/2-Tscc)/(Dcon/2+Tscc))', 'Capacitance per phase (analytic)');
model.param('par3').set('Icpha', 'w0*Cpha*V0', 'Charging current per phase (analytic)');

model.geom('geom1').create('c1', 'Circle');
model.geom('geom1').feature('c1').label('Phases');
model.geom('geom1').feature('c1').set('r', 'Dcon/2');
model.geom('geom1').feature('c1').set('pos', {'Dpha/sqrt(3)' '0'});
model.geom('geom1').feature('c1').set('selresult', true);
model.geom('geom1').run('c1');
model.geom('geom1').feature.duplicate('c2', 'c1');
model.geom('geom1').feature('c2').label('Screens');
model.geom('geom1').feature('c2').set('type', 'curve');
model.geom('geom1').feature('c2').set('r', 'Dins/2+Tpbs');
model.geom('geom1').feature('c2').setIndex('layer', 'Tpbs', 0);
model.geom('geom1').run('c2');
model.geom('geom1').create('rot1', 'Rotate');
model.geom('geom1').feature('rot1').selection('input').set({'c1' 'c2'});
model.geom('geom1').feature('rot1').set('rot', '0[deg], 120[deg], 240[deg]');
model.geom('geom1').run('rot1');
model.geom('geom1').create('uni1', 'Union');
model.geom('geom1').feature('uni1').selection('input').set({'rot1'});
model.geom('geom1').feature('uni1').set('intbnd', false);
model.geom('geom1').run('uni1');
model.geom('geom1').create('c3', 'Circle');
model.geom('geom1').feature('c3').label('Cable Armor');
model.geom('geom1').feature('c3').set('r', 'Tarm/2');
model.geom('geom1').feature('c3').set('pos', {'Darm/2' '0'});
model.geom('geom1').feature('c3').set('selresult', true);
model.geom('geom1').run('c3');
model.geom('geom1').create('rot2', 'Rotate');
model.geom('geom1').feature('rot2').selection('input').named('c3');
model.geom('geom1').feature('rot2').set('rot', '360[deg]*range(1/Narm,1/Narm,1)');
model.geom('geom1').run('rot2');
model.geom('geom1').create('c4', 'Circle');
model.geom('geom1').feature('c4').label('Cable Domains');
model.geom('geom1').feature('c4').set('r', 'Dcab/2');
model.geom('geom1').feature('c4').set('selresult', true);
model.geom('geom1').run('c4');
model.geom('geom1').feature.duplicate('c5', 'c4');
model.geom('geom1').feature('c5').label('Electromagnetic Domains');
model.geom('geom1').feature('c5').set('r', '5*Dcab/2');
model.geom('geom1').run('fin');

model.selection.create('uni1', 'Union');
model.selection('uni1').model('comp1');
model.selection('uni1').label('Metals');
model.selection('uni1').set('input', {'geom1_c1_dom' 'geom1_c2_dom' 'geom1_c3_dom'});

model.physics('mf').create('als1', 'AmperesLawSolid', 2);
model.physics('mf').feature('als1').selection.named('uni1');

model.view('view1').set('showmaterial', true);

model.material.create('mat1', 'Common', 'comp1');
model.material('mat1').propertyGroup('def').func.create('eta', 'Piecewise');
model.material('mat1').propertyGroup('def').func.create('Cp', 'Piecewise');
model.material('mat1').propertyGroup('def').func.create('rho', 'Analytic');
model.material('mat1').propertyGroup('def').func.create('k', 'Piecewise');
model.material('mat1').propertyGroup('def').func.create('cs', 'Analytic');
model.material('mat1').propertyGroup('def').func.create('an1', 'Analytic');
model.material('mat1').propertyGroup('def').func.create('an2', 'Analytic');
model.material('mat1').propertyGroup.create('RefractiveIndex', 'Refractive index');
model.material('mat1').propertyGroup.create('NonlinearModel', 'Nonlinear model');
model.material('mat1').propertyGroup.create('idealGas', 'Ideal gas');
model.material('mat1').propertyGroup('idealGas').func.create('Cp', 'Piecewise');
model.material('mat1').label('Air');
model.material('mat1').set('family', 'air');
model.material('mat1').propertyGroup('def').func('eta').set('arg', 'T');
model.material('mat1').propertyGroup('def').func('eta').set('pieces', {'200.0' '1600.0' '-8.38278E-7+8.35717342E-8*T^1-7.69429583E-11*T^2+4.6437266E-14*T^3-1.06585607E-17*T^4'});
model.material('mat1').propertyGroup('def').func('eta').set('argunit', 'K');
model.material('mat1').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.material('mat1').propertyGroup('def').func('Cp').set('arg', 'T');
model.material('mat1').propertyGroup('def').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.material('mat1').propertyGroup('def').func('Cp').set('argunit', 'K');
model.material('mat1').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.material('mat1').propertyGroup('def').func('rho').set('expr', 'pA*0.02897/R_const[K*mol/J]/T');
model.material('mat1').propertyGroup('def').func('rho').set('args', {'pA' 'T'});
model.material('mat1').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.material('mat1').propertyGroup('def').func('rho').set('argunit', {'Pa' 'K'});
model.material('mat1').propertyGroup('def').func('rho').set('plotaxis', {'off' 'on'});
model.material('mat1').propertyGroup('def').func('rho').set('plotfixedvalue', {'101325' '273.15'});
model.material('mat1').propertyGroup('def').func('rho').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '293.15'});
model.material('mat1').propertyGroup('def').func('k').set('arg', 'T');
model.material('mat1').propertyGroup('def').func('k').set('pieces', {'200.0' '1600.0' '-0.00227583562+1.15480022E-4*T^1-7.90252856E-8*T^2+4.11702505E-11*T^3-7.43864331E-15*T^4'});
model.material('mat1').propertyGroup('def').func('k').set('argunit', 'K');
model.material('mat1').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.material('mat1').propertyGroup('def').func('cs').set('expr', 'sqrt(1.4*R_const[K*mol/J]/0.02897*T)');
model.material('mat1').propertyGroup('def').func('cs').set('args', {'T'});
model.material('mat1').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.material('mat1').propertyGroup('def').func('cs').set('argunit', {'K'});
model.material('mat1').propertyGroup('def').func('cs').set('plotfixedvalue', {'273.15'});
model.material('mat1').propertyGroup('def').func('cs').set('plotargs', {'T' '273.15' '373.15'});
model.material('mat1').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.material('mat1').propertyGroup('def').func('an1').set('expr', '-1/rho(pA,T)*d(rho(pA,T),T)');
model.material('mat1').propertyGroup('def').func('an1').set('args', {'pA' 'T'});
model.material('mat1').propertyGroup('def').func('an1').set('fununit', '1/K');
model.material('mat1').propertyGroup('def').func('an1').set('argunit', {'Pa' 'K'});
model.material('mat1').propertyGroup('def').func('an1').set('plotaxis', {'off' 'on'});
model.material('mat1').propertyGroup('def').func('an1').set('plotfixedvalue', {'101325' '273.15'});
model.material('mat1').propertyGroup('def').func('an1').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '373.15'});
model.material('mat1').propertyGroup('def').func('an2').set('funcname', 'muB');
model.material('mat1').propertyGroup('def').func('an2').set('expr', '0.6*eta(T)');
model.material('mat1').propertyGroup('def').func('an2').set('args', {'T'});
model.material('mat1').propertyGroup('def').func('an2').set('fununit', 'Pa*s');
model.material('mat1').propertyGroup('def').func('an2').set('argunit', {'K'});
model.material('mat1').propertyGroup('def').func('an2').set('plotfixedvalue', {'200'});
model.material('mat1').propertyGroup('def').func('an2').set('plotargs', {'T' '200' '1600'});
model.material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.material('mat1').propertyGroup('def').set('molarmass', '');
model.material('mat1').propertyGroup('def').set('bulkviscosity', '');
model.material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)'});
model.material('mat1').propertyGroup('def').set('molarmass', '0.02897[kg/mol]');
model.material('mat1').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.material('mat1').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.material('mat1').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.material('mat1').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.material('mat1').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.material('mat1').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.material('mat1').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.material('mat1').propertyGroup('def').set('density', 'rho(pA,T)');
model.material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.material('mat1').propertyGroup('def').set('soundspeed', 'cs(T)');
model.material('mat1').propertyGroup('def').addInput('temperature');
model.material('mat1').propertyGroup('def').addInput('pressure');
model.material('mat1').propertyGroup('RefractiveIndex').set('n', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.material('mat1').propertyGroup('NonlinearModel').set('BA', 'def.gamma-1');
model.material('mat1').propertyGroup('idealGas').func('Cp').label('Piecewise 2');
model.material('mat1').propertyGroup('idealGas').func('Cp').set('arg', 'T');
model.material('mat1').propertyGroup('idealGas').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.material('mat1').propertyGroup('idealGas').func('Cp').set('argunit', 'K');
model.material('mat1').propertyGroup('idealGas').func('Cp').set('fununit', 'J/(kg*K)');
model.material('mat1').propertyGroup('idealGas').set('Rs', 'R_const/Mn');
model.material('mat1').propertyGroup('idealGas').set('heatcapacity', 'Cp(T)');
model.material('mat1').propertyGroup('idealGas').set('ratioofspecificheat', '1.4');
model.material('mat1').propertyGroup('idealGas').set('molarmass', '0.02897');
model.material('mat1').propertyGroup('idealGas').addInput('temperature');
model.material('mat1').propertyGroup('idealGas').addInput('pressure');
model.material('mat1').materialType('nonSolid');
model.material.create('mat2', 'Common', 'comp1');
model.material('mat2').label('Copper');
model.material('mat2').selection.set([2]);
model.material('mat2').selection.named('geom1_c1_dom');
model.material('mat2').set('family', 'copper');
model.material.create('mat3', 'Common', 'comp1');
model.material('mat3').label('Lead');
model.material('mat3').selection.named('geom1_c2_dom');
model.material('mat3').set('family', 'lead');
model.material.create('mat4', 'Common', 'comp1');
model.material('mat4').label('Galvanized steel');
model.material('mat4').selection.named('geom1_c3_dom');
model.material('mat4').set('family', 'steel');
model.material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'x'});
model.material('mat1').propertyGroup('def').set('molarmass', {'x'});
model.material('mat1').propertyGroup('def').set('bulkviscosity', {'x'});
model.material('mat1').propertyGroup('def').set('relpermeability', {'x'});
model.material('mat1').propertyGroup('def').set('relpermittivity', {'x'});
model.material('mat1').propertyGroup('def').set('dynamicviscosity', {'x'});
model.material('mat1').propertyGroup('def').set('ratioofspecificheat', {'x'});
model.material('mat1').propertyGroup('def').set('electricconductivity', {'x'});
model.material('mat1').propertyGroup('def').set('heatcapacity', {'x'});
model.material('mat1').propertyGroup('def').set('density', {'x'});
model.material('mat1').propertyGroup('def').set('thermalconductivity', {'x'});
model.material('mat1').propertyGroup('def').set('soundspeed', {'x'});
model.material('mat1').propertyGroup('RefractiveIndex').set('n', {'x'});
model.material('mat1').propertyGroup('RefractiveIndex').set('ki', {'x'});
model.material('mat1').propertyGroup('NonlinearModel').set('BA', {'x'});
model.material('mat1').propertyGroup('idealGas').set('Rs', {'x'});
model.material('mat1').propertyGroup('idealGas').set('heatcapacity', {'x'});
model.material('mat1').propertyGroup('idealGas').set('ratioofspecificheat', {'x'});
model.material('mat1').propertyGroup('idealGas').set('molarmass', {'x'});
model.material.label('Materials ');
model.material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)'});
model.material('mat1').propertyGroup('def').set('molarmass', {'0.02897[kg/mol]'});
model.material('mat1').propertyGroup('def').set('bulkviscosity', {'muB(T)'});
model.material('mat1').propertyGroup('def').set('relpermeability', {'1'});
model.material('mat1').propertyGroup('def').set('relpermittivity', {'1'});
model.material('mat1').propertyGroup('def').set('dynamicviscosity', {'eta(T)'});
model.material('mat1').propertyGroup('def').set('ratioofspecificheat', {'1.4'});
model.material('mat1').propertyGroup('def').set('electricconductivity', {'1e-14[S/m]'});
model.material('mat1').propertyGroup('def').set('heatcapacity', {'Cp(T)'});
model.material('mat1').propertyGroup('def').set('density', {'rho(pA,T)'});
model.material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)'});
model.material('mat1').propertyGroup('def').set('soundspeed', {'cs(T)'});
model.material('mat1').propertyGroup('RefractiveIndex').set('n', {'1'});
model.material('mat1').propertyGroup('RefractiveIndex').set('ki', {'0'});
model.material('mat1').propertyGroup('NonlinearModel').set('BA', {'(def.gamma+1)/2'});
model.material('mat1').propertyGroup('idealGas').set('Rs', {'R_const/Mn'});
model.material('mat1').propertyGroup('idealGas').set('heatcapacity', {'Cp(T)'});
model.material('mat1').propertyGroup('idealGas').set('ratioofspecificheat', {'1.4'});
model.material('mat1').propertyGroup('idealGas').set('molarmass', {'0.02897'});
model.material('mat2').propertyGroup('def').set('relpermeability', {'Mcup'});
model.material('mat2').propertyGroup('def').set('electricconductivity', {'Ncon*Scup'});
model.material('mat2').propertyGroup('def').set('relpermittivity', {'1'});
model.material('mat3').propertyGroup('def').set('relpermeability', {'Mpbs'});
model.material('mat3').propertyGroup('def').set('electricconductivity', {'Spbs'});
model.material('mat3').propertyGroup('def').set('relpermittivity', {'1'});
model.material('mat4').propertyGroup('def').set('relpermeability', {'Marm'});
model.material('mat4').propertyGroup('def').set('electricconductivity', {'Sarm'});
model.material('mat4').propertyGroup('def').set('relpermittivity', {'1'});
model.material.label('Materials');

model.physics('mf').label('Magnetic Fields, Section 1');
model.physics('mf').prop('d').set('d', 'Lsec1*Lcab');
model.physics('mf').create('coil1', 'Coil', 2);
model.physics('mf').feature('coil1').label('Phase 1');
model.physics('mf').feature('coil1').selection.set([51]);
model.physics('mf').feature('coil1').set('ICoil', 'I0');
model.physics('mf').create('coil2', 'Coil', 2);
model.physics('mf').feature('coil2').label('Phase 2');
model.physics('mf').feature('coil2').selection.set([80]);
model.physics('mf').feature('coil2').set('ICoil', 'I0*exp(-120[deg]*j)');
model.physics('mf').create('coil3', 'Coil', 2);
model.physics('mf').feature('coil3').label('Phase 3');
model.physics('mf').feature('coil3').selection.set([50]);
model.physics('mf').feature('coil3').set('ICoil', 'I0*exp(+120[deg]*j)');

model.study('std1').feature('freq').set('plist', 'f0');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'freq');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'freq');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').feature.remove('pDef');
model.sol('sol1').feature('s1').feature('p1').set('pname', {'freq'});
model.sol('sol1').feature('s1').feature('p1').set('plistarr', {'f0'});
model.sol('sol1').feature('s1').feature('p1').set('punit', {'Hz'});
model.sol('sol1').feature('s1').feature('p1').set('pcontinuationmode', 'no');
model.sol('sol1').feature('s1').feature('p1').set('preusesol', 'no');
model.sol('sol1').feature('s1').feature('p1').set('pdistrib', 'off');
model.sol('sol1').feature('s1').feature('p1').set('plot', 'off');
model.sol('sol1').feature('s1').feature('p1').set('plotgroup', 'Default');
model.sol('sol1').feature('s1').feature('p1').set('probesel', 'all');
model.sol('sol1').feature('s1').feature('p1').set('probes', {});
model.sol('sol1').feature('s1').feature('p1').set('control', 'freq');
model.sol('sol1').feature('s1').set('linpmethod', 'sol');
model.sol('sol1').feature('s1').set('linpsol', 'zero');
model.sol('sol1').feature('s1').set('control', 'freq');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');
model.sol('sol1').runAll;

model.result.create('pg1', 'PlotGroup2D');
model.result('pg1').label('Magnetic Flux Density Norm (mf)');
model.result('pg1').set('frametype', 'spatial');
model.result('pg1').set('showlegendsmaxmin', true);
model.result('pg1').set('data', 'dset1');
model.result('pg1').setIndex('looplevel', 1, 0);
model.result('pg1').set('defaultPlotID', 'InterfaceComponents/PlotDefaults/icom6/pdef1/pcond2/pcond2/pg1');
model.result('pg1').feature.create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('showsolutionparams', 'on');
model.result('pg1').feature('surf1').set('solutionparams', 'parent');
model.result('pg1').feature('surf1').set('colortable', 'Prism');
model.result('pg1').feature('surf1').set('colortabletrans', 'nonlinear');
model.result('pg1').feature('surf1').set('colorcalibration', -0.8);
model.result('pg1').feature('surf1').set('showsolutionparams', 'on');
model.result('pg1').feature('surf1').set('data', 'parent');
model.result('pg1').feature.create('str1', 'Streamline');
model.result('pg1').feature('str1').set('showsolutionparams', 'on');
model.result('pg1').feature('str1').set('solutionparams', 'parent');
model.result('pg1').feature('str1').set('titletype', 'none');
model.result('pg1').feature('str1').set('posmethod', 'uniform');
model.result('pg1').feature('str1').set('udist', 0.03);
model.result('pg1').feature('str1').set('maxlen', 0.4);
model.result('pg1').feature('str1').set('maxtime', Inf);
model.result('pg1').feature('str1').set('inheritcolor', false);
model.result('pg1').feature('str1').set('showsolutionparams', 'on');
model.result('pg1').feature('str1').set('maxtime', Inf);
model.result('pg1').feature('str1').set('showsolutionparams', 'on');
model.result('pg1').feature('str1').set('maxtime', Inf);
model.result('pg1').feature('str1').set('showsolutionparams', 'on');
model.result('pg1').feature('str1').set('maxtime', Inf);
model.result('pg1').feature('str1').set('showsolutionparams', 'on');
model.result('pg1').feature('str1').set('maxtime', Inf);
model.result('pg1').feature('str1').set('data', 'parent');
model.result('pg1').feature('str1').selection.geom('geom1', 1);
model.result('pg1').feature('str1').selection.set([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484]);
model.result('pg1').feature('str1').set('inheritplot', 'surf1');
model.result('pg1').feature('str1').feature.create('col1', 'Color');
model.result('pg1').feature('str1').feature('col1').set('colortable', 'PrismDark');
model.result('pg1').feature('str1').feature('col1').set('colorlegend', false);
model.result('pg1').feature('str1').feature('col1').set('colortabletrans', 'nonlinear');
model.result('pg1').feature('str1').feature('col1').set('colorcalibration', -0.8);
model.result('pg1').feature('str1').feature.create('filt1', 'Filter');
model.result('pg1').feature('str1').feature('filt1').set('expr', '!isScalingSystemDomain');
model.result('pg1').feature.create('con1', 'Contour');
model.result('pg1').feature('con1').set('showsolutionparams', 'on');
model.result('pg1').feature('con1').set('solutionparams', 'parent');
model.result('pg1').feature('con1').set('expr', 'mf.Az');
model.result('pg1').feature('con1').set('titletype', 'none');
model.result('pg1').feature('con1').set('number', 10);
model.result('pg1').feature('con1').set('levelrounding', false);
model.result('pg1').feature('con1').set('coloring', 'uniform');
model.result('pg1').feature('con1').set('colorlegend', false);
model.result('pg1').feature('con1').set('color', 'custom');
model.result('pg1').feature('con1').set('customcolor', [0.3764705955982208 0.3764705955982208 0.3764705955982208]);
model.result('pg1').feature('con1').set('resolution', 'fine');
model.result('pg1').feature('con1').set('inheritcolor', false);
model.result('pg1').feature('con1').set('showsolutionparams', 'on');
model.result('pg1').feature('con1').set('data', 'parent');
model.result('pg1').feature('con1').set('inheritplot', 'surf1');
model.result('pg1').feature('con1').feature.create('filt1', 'Filter');
model.result('pg1').feature('con1').feature('filt1').set('expr', '!isScalingSystemDomain');
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('surf1').set('colorcalibration', -1.5);
model.result('pg1').run;
model.result('pg1').feature('str1').active(false);
model.result('pg1').run;
model.result('pg1').feature('con1').set('number', 20);
model.result('pg1').run;
model.result.numerical.create('int1', 'IntSurface');
model.result.numerical('int1').set('intvolume', true);
model.result.numerical('int1').label('Phase Losses');
model.result.numerical('int1').selection.set([2]);
model.result.numerical('int1').selection.named('geom1_c1_dom');
model.result.numerical('int1').setIndex('expr', 'mf.Qh', 0);
model.result.numerical('int1').setIndex('unit', 'W/km', 0);
model.result.numerical('int1').setIndex('descr', 'Phase losses (solid bonding)', 0);
model.result.table.create('tbl1', 'Table');
model.result.table('tbl1').comments('Phase Losses');
model.result.numerical('int1').set('table', 'tbl1');
model.result.numerical('int1').setResult;
model.result.numerical.create('int2', 'IntSurface');
model.result.numerical('int2').set('intvolume', true);
model.result.numerical('int2').label('Screen Losses');
model.result.numerical('int2').selection.named('geom1_c2_dom');
model.result.numerical('int2').setIndex('expr', 'mf.Qh', 0);
model.result.numerical('int2').setIndex('unit', 'W/km', 0);
model.result.numerical('int2').setIndex('descr', 'Screen losses (solid bonding)', 0);
model.result.table.create('tbl2', 'Table');
model.result.table('tbl2').comments('Screen Losses');
model.result.numerical('int2').set('table', 'tbl2');
model.result.numerical('int2').setResult;
model.result.numerical.create('gev1', 'EvalGlobal');
model.result.numerical('gev1').label('Phase AC Resistance');
model.result.numerical('gev1').setIndex('expr', '(mf.RCoil_1+mf.RCoil_2+mf.RCoil_3)/(3*Lsec1*Lcab)', 0);
model.result.numerical('gev1').setIndex('unit', 'mohm/km', 0);
model.result.numerical('gev1').setIndex('descr', 'Phase AC resistance (solid bonding)', 0);
model.result.table.create('tbl3', 'Table');
model.result.table('tbl3').comments('Phase AC Resistance');
model.result.numerical('gev1').set('table', 'tbl3');
model.result.numerical('gev1').setResult;
model.result.numerical.create('gev2', 'EvalGlobal');
model.result.numerical('gev2').label('Phase Inductance');
model.result.numerical('gev2').setIndex('expr', '(mf.LCoil_1+mf.LCoil_2+mf.LCoil_3)/(3*Lsec1*Lcab)', 0);
model.result.numerical('gev2').setIndex('unit', 'mH/km', 0);
model.result.numerical('gev2').setIndex('descr', 'Phase inductance (solid bonding)', 0);
model.result.table.create('tbl4', 'Table');
model.result.table('tbl4').comments('Phase Inductance');
model.result.numerical('gev2').set('table', 'tbl4');
model.result.numerical('gev2').setResult;

model.physics('mf').create('coil4', 'Coil', 2);
model.physics('mf').feature('coil4').label('Screen 1');
model.physics('mf').feature('coil4').selection.set([37]);
model.physics('mf').feature('coil4').set('ICoil', '0[A]');
model.physics('mf').create('coil5', 'Coil', 2);
model.physics('mf').feature('coil5').label('Screen 2');
model.physics('mf').feature('coil5').selection.set([68]);
model.physics('mf').feature('coil5').set('ICoil', '0[A]');
model.physics('mf').create('coil6', 'Coil', 2);
model.physics('mf').feature('coil6').label('Screen 3');
model.physics('mf').feature('coil6').selection.set([36]);
model.physics('mf').feature('coil6').set('ICoil', '0[A]');

model.sol('sol1').study('std1');
model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'freq');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'freq');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').feature.remove('pDef');
model.sol('sol1').feature('s1').feature('p1').set('pname', {'freq'});
model.sol('sol1').feature('s1').feature('p1').set('plistarr', {'f0'});
model.sol('sol1').feature('s1').feature('p1').set('punit', {'Hz'});
model.sol('sol1').feature('s1').feature('p1').set('pcontinuationmode', 'no');
model.sol('sol1').feature('s1').feature('p1').set('preusesol', 'no');
model.sol('sol1').feature('s1').feature('p1').set('pdistrib', 'off');
model.sol('sol1').feature('s1').feature('p1').set('plot', 'off');
model.sol('sol1').feature('s1').feature('p1').set('plotgroup', 'pg1');
model.sol('sol1').feature('s1').feature('p1').set('probesel', 'all');
model.sol('sol1').feature('s1').feature('p1').set('probes', {});
model.sol('sol1').feature('s1').feature('p1').set('control', 'freq');
model.sol('sol1').feature('s1').set('linpmethod', 'sol');
model.sol('sol1').feature('s1').set('linpsol', 'zero');
model.sol('sol1').feature('s1').set('control', 'freq');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');
model.sol('sol1').runAll;

model.result('pg1').run;
model.result.numerical('int1').setIndex('descr', 'Phase losses (single-point bonding)', 0);
model.result.numerical('int1').set('table', 'tbl1');
model.result.numerical('int1').appendResult;
model.result.numerical('int2').setIndex('descr', 'Screen losses (single-point bonding)', 0);
model.result.numerical('int2').set('table', 'tbl2');
model.result.numerical('int2').appendResult;
model.result.numerical('gev1').setIndex('descr', 'Phase AC resistance (single-point bonding)', 0);
model.result.numerical('gev1').set('table', 'tbl3');
model.result.numerical('gev1').appendResult;
model.result.numerical('gev2').setIndex('descr', 'Phase inductance (single-point bonding)', 0);
model.result.numerical('gev2').set('table', 'tbl4');
model.result.numerical('gev2').appendResult;
model.result.numerical.create('gev3', 'EvalGlobal');
model.result.numerical('gev3').label('Screen Voltage');
model.result.numerical('gev3').setIndex('expr', 'abs(mf.VCoil_4)', 0);
model.result.numerical('gev3').setIndex('descr', 'Voltage across screen 1 (single-point bonding)', 0);
model.result.numerical('gev3').setIndex('expr', 'abs(mf.VCoil_5)', 1);
model.result.numerical('gev3').setIndex('descr', 'Voltage across screen 2 (single-point bonding)', 1);
model.result.numerical('gev3').setIndex('expr', 'abs(mf.VCoil_6)', 2);
model.result.numerical('gev3').setIndex('descr', 'Voltage across screen 3 (single-point bonding)', 2);
model.result.table.create('tbl5', 'Table');
model.result.table('tbl5').comments('Screen Voltage');
model.result.numerical('gev3').set('table', 'tbl5');
model.result.numerical('gev3').setResult;

model.param('par2').set('Lsec1', '1/3');
model.param('par2').set('Lsec3', '1/3');

model.physics.create('mf2', 'InductionCurrents', 'geom1');
model.physics('mf2').model('comp1');

model.study('std1').feature('freq').setSolveFor('/physics/mf2', true);

model.physics.create('mf3', 'InductionCurrents', 'geom1');
model.physics('mf3').model('comp1');

model.study('std1').feature('freq').setSolveFor('/physics/mf3', true);

model.physics.create('cir', 'Circuit', 'geom1');
model.physics('cir').model('comp1');

model.study('std1').feature('freq').setSolveFor('/physics/cir', true);

model.physics('mf2').label('Magnetic Fields, Section 2');
model.physics('mf2').prop('d').set('d', 'Lsec2*Lcab');
model.physics('mf3').label('Magnetic Fields, Section 3');
model.physics('mf3').prop('d').set('d', 'Lsec3*Lcab');
model.physics('mf').feature('coil4').set('CoilExcitation', 'CircuitCurrent');
model.physics('mf').feature('coil5').set('CoilExcitation', 'CircuitCurrent');
model.physics('mf').feature('coil6').set('CoilExcitation', 'CircuitCurrent');
model.physics('mf2').feature.copy('als1', 'mf/als1');
model.physics('mf2').feature.copy('coil1', 'mf/coil1');
model.physics('mf2').feature.copy('coil2', 'mf/coil2');
model.physics('mf2').feature.copy('coil3', 'mf/coil3');
model.physics('mf2').feature.copy('coil4', 'mf/coil4');
model.physics('mf2').feature.copy('coil5', 'mf/coil5');
model.physics('mf2').feature.copy('coil6', 'mf/coil6');
model.physics('mf3').feature.copy('als1', 'mf/als1');
model.physics('mf3').feature.copy('coil1', 'mf/coil1');
model.physics('mf3').feature.copy('coil2', 'mf/coil2');
model.physics('mf3').feature.copy('coil3', 'mf/coil3');
model.physics('mf3').feature.copy('coil4', 'mf/coil4');
model.physics('mf3').feature.copy('coil5', 'mf/coil5');
model.physics('mf3').feature.copy('coil6', 'mf/coil6');
model.physics('cir').create('IvsU1', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU1').setIndex('Connections', 11, 0, 0);
model.physics('cir').feature('IvsU1').setIndex('Connections', 0, 1, 0);
model.physics('cir').feature('IvsU1').set('V_src', 'root.comp1.mf.VCoil_4');
model.physics('cir').create('IvsU2', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU2').setIndex('Connections', 12, 0, 0);
model.physics('cir').feature('IvsU2').setIndex('Connections', 11, 1, 0);
model.physics('cir').feature('IvsU2').set('V_src', 'root.comp1.mf2.VCoil_5');
model.physics('cir').create('IvsU3', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU3').setIndex('Connections', 13, 0, 0);
model.physics('cir').feature('IvsU3').setIndex('Connections', 12, 1, 0);
model.physics('cir').feature('IvsU3').set('V_src', 'root.comp1.mf3.VCoil_6');
model.physics('cir').create('R1', 'Resistor', -1);
model.physics('cir').feature('R1').setIndex('Connections', 0, 0, 0);
model.physics('cir').feature('R1').setIndex('Connections', 13, 1, 0);
model.physics('cir').feature('R1').set('R', '1[uohm]');
model.physics('cir').create('IvsU4', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU4').setIndex('Connections', 21, 0, 0);
model.physics('cir').feature('IvsU4').setIndex('Connections', 0, 1, 0);
model.physics('cir').feature('IvsU4').set('V_src', 'root.comp1.mf.VCoil_5');
model.physics('cir').create('IvsU5', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU5').setIndex('Connections', 22, 0, 0);
model.physics('cir').feature('IvsU5').setIndex('Connections', 21, 1, 0);
model.physics('cir').feature('IvsU5').set('V_src', 'root.comp1.mf2.VCoil_6');
model.physics('cir').create('IvsU6', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU6').setIndex('Connections', 23, 0, 0);
model.physics('cir').feature('IvsU6').setIndex('Connections', 22, 1, 0);
model.physics('cir').feature('IvsU6').set('V_src', 'root.comp1.mf3.VCoil_4');
model.physics('cir').create('R2', 'Resistor', -1);
model.physics('cir').feature('R2').setIndex('Connections', 0, 0, 0);
model.physics('cir').feature('R2').setIndex('Connections', 23, 1, 0);
model.physics('cir').feature('R2').set('R', '1[uohm]');
model.physics('cir').create('IvsU7', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU7').setIndex('Connections', 31, 0, 0);
model.physics('cir').feature('IvsU7').setIndex('Connections', 0, 1, 0);
model.physics('cir').feature('IvsU7').set('V_src', 'root.comp1.mf.VCoil_6');
model.physics('cir').create('IvsU8', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU8').setIndex('Connections', 32, 0, 0);
model.physics('cir').feature('IvsU8').setIndex('Connections', 31, 1, 0);
model.physics('cir').feature('IvsU8').set('V_src', 'root.comp1.mf2.VCoil_4');
model.physics('cir').create('IvsU9', 'ModelDeviceIV', -1);
model.physics('cir').feature('IvsU9').setIndex('Connections', 33, 0, 0);
model.physics('cir').feature('IvsU9').setIndex('Connections', 32, 1, 0);
model.physics('cir').feature('IvsU9').set('V_src', 'root.comp1.mf3.VCoil_5');
model.physics('cir').create('R3', 'Resistor', -1);
model.physics('cir').feature('R3').setIndex('Connections', 0, 0, 0);
model.physics('cir').feature('R3').setIndex('Connections', 33, 1, 0);
model.physics('cir').feature('R3').set('R', '1[uohm]');

model.sol('sol1').study('std1');
model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'freq');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'freq');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').feature.remove('pDef');
model.sol('sol1').feature('s1').feature('p1').set('pname', {'freq'});
model.sol('sol1').feature('s1').feature('p1').set('plistarr', {'f0'});
model.sol('sol1').feature('s1').feature('p1').set('punit', {'Hz'});
model.sol('sol1').feature('s1').feature('p1').set('pcontinuationmode', 'no');
model.sol('sol1').feature('s1').feature('p1').set('preusesol', 'no');
model.sol('sol1').feature('s1').feature('p1').set('pdistrib', 'off');
model.sol('sol1').feature('s1').feature('p1').set('plot', 'off');
model.sol('sol1').feature('s1').feature('p1').set('plotgroup', 'pg1');
model.sol('sol1').feature('s1').feature('p1').set('probesel', 'all');
model.sol('sol1').feature('s1').feature('p1').set('probes', {});
model.sol('sol1').feature('s1').feature('p1').set('control', 'freq');
model.sol('sol1').feature('s1').set('linpmethod', 'sol');
model.sol('sol1').feature('s1').set('linpsol', 'zero');
model.sol('sol1').feature('s1').set('control', 'freq');
model.sol('sol1').feature('s1').create('seDef', 'Segregated');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').feature('s1').feature.remove('seDef');
model.sol('sol1').attach('std1');
model.sol('sol1').runAll;

model.result('pg1').run;
model.result.numerical('int1').setIndex('descr', 'Phase losses (cross bonding)', 0);
model.result.numerical('int1').set('table', 'tbl1');
model.result.numerical('int1').appendResult;
model.result.numerical('int2').setIndex('descr', 'Screen losses (cross bonding)', 0);
model.result.numerical('int2').set('table', 'tbl2');
model.result.numerical('int2').appendResult;
model.result.numerical('gev1').setIndex('descr', 'Phase AC resistance (cross bonding)', 0);
model.result.numerical('gev1').set('table', 'tbl3');
model.result.numerical('gev1').appendResult;
model.result.numerical('gev2').setIndex('descr', 'Phase inductance (cross bonding)', 0);
model.result.numerical('gev2').set('table', 'tbl4');
model.result.numerical('gev2').appendResult;
model.result.numerical('gev3').setIndex('descr', 'Voltage across screen 1 (cross bonding)', 0);
model.result.numerical('gev3').setIndex('descr', 'Voltage across screen 2 (cross bonding)', 1);
model.result.numerical('gev3').setIndex('descr', 'Voltage across screen 3 (cross bonding)', 2);
model.result.numerical('gev3').set('table', 'tbl5');
model.result.numerical('gev3').appendResult;
model.result('pg1').run;
model.result('pg1').run;

model.title(['Submarine Cable 5 ' native2unicode(hex2dec({'20' '14'}), 'unicode') ' Bonding Inductive']);

model.description(['In the Inductive Effects tutorial (the previous tutorial in this series), the Coil group option is mentioned as a means to mimic the effects of cross bonding, but the exact extent of the validity of this approach is not shown. In order to investigate the different bonding types more closely, this tutorial considers three sections of cable individually, represented by three separate Magnetic Fields interfaces.' newline  newline 'The model uses a strongly simplified geometry. Even so, the results correspond very well to those from the Inductive Effects tutorial. This justifies both the simplified geometry in this tutorial, as well as the cross-bonding approach suggested in the Inductive Effects tutorial. Finally, as opposed to the other inductive models in this series, this one allows for investigating dissimilar section lengths.']);

model.label('submarine_cable_05_bonding_inductive.mph');

model.modelNode.label('Components');

out = model;
