function out = model
%
% tweeter_shape_optimization_geom_sequence.m
%
% Model exported on May 26 2025, 21:25 by COMSOL 6.2.0.339.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/Applications/COMSOL62/Multiphysics/applications/Acoustics_Module/Optimization');

model.modelNode.create('comp1', true);

model.geom.create('geom1', 2);
model.geom('geom1').model('comp1');
model.geom('geom1').axisymmetric(true);

model.mesh.create('mesh1', 'geom1');

% To import content from file, use:
% model.param.loadFile('FILENAME');
model.param.set('r_model', 'sin(angle_eval/2)*r_eval+2*th_pml', 'Radius of the acoustic domain');
model.param.set('h_model', 'r_eval-(-h_former+h_voice_coil/2-h_top_plate/2-h_back-h_waveguide)+2*th_pml', 'Height of the acoustic domain');
model.param.set('th_pml', '5[mm]', 'Thickness of the PML layer');
model.param.set('d_voice_coil', '25[mm]', 'Radius of the voice coil');
model.param.set('h_voice_coil', '3[mm]', 'Height of the voice coil');
model.param.set('th_voice_coil', '0.5[mm]', 'Thickness of the voice coil');
model.param.set('h_former', '15[mm]', 'Height of the former');
model.param.set('h_top_plate', '6[mm]', 'Height of the pole piece');
model.param.set('air_gap', '0.5[mm]', 'Air gap');
model.param.set('h_back', '8[mm]', 'Height of the back volume');
model.param.set('d_magnet', '30[mm]', 'Inner diameter of the magnet');
model.param.set('r1_susp', '0.5[mm]', 'Minimum radius of the suspensions');
model.param.set('r2_susp', '1[mm]', 'Maximum radius of the suspensions');
model.param.set('d_waveguide', '100[mm]', 'Diameter of the waveguide');
model.param.set('d1', '12.5[mm]', 'First dome dimension');
model.param.set('d2', '12[mm]', 'Second dome dimension');
model.param.set('d3', '10.5[mm]', 'Third dome dimension');
model.param.set('d4', '8[mm]', 'Fourth dome dimension');
model.param.set('d5', '4.5[mm]', 'Fifth dome dimension');
model.param.set('alpha1', '0[deg]', 'Axis dome angle');
model.param.set('alpha2', '60[deg]', 'Final dome angle');
model.param.set('w1', '8[mm]', 'First waveguide dimension');
model.param.set('w2', '11[mm]', 'Second waveguide dimension');
model.param.set('w3', '14.25[mm]', 'Third waveguide dimension');
model.param.set('w4', '17[mm]', 'Fourth waveguide dimension');
model.param.set('beta1', '90[deg]', 'Initial waveguide Angle');
model.param.set('beta2', '30[deg]', 'Final waveguide angle');
model.param.set('h_waveguide', '20[mm]', 'Height of the waveguide');
model.param.set('d_porous', '18[mm]', 'Diameter of the porous absorber');
model.param.set('h_porous', '7[mm]', 'Height of the porous absorber');
model.param.set('r_eval', '600[mm]', 'Radius of evaluation of the near field');
model.param.set('angle_eval', '20[deg]', 'Angle width in front of the speaker');

model.geom('geom1').lengthUnit('mm');
model.geom('geom1').create('c1', 'Circle');
model.geom('geom1').feature('c1').set('angle', 90);
model.geom('geom1').feature('c1').set('r', 'r_model+th_pml');
model.geom('geom1').feature('c1').setIndex('layer', 'th_pml', 0);
model.geom('geom1').run('c1');
model.geom('geom1').create('r1', 'Rectangle');
model.geom('geom1').feature('r1').set('size', {'r_model+th_pml' '1'});
model.geom('geom1').feature('r1').setIndex('size', 'r_model+th_pml+h_former-h_voice_coil/2+h_top_plate/2+h_back+h_waveguide', 1);
model.geom('geom1').feature('r1').set('pos', {'0' '-h_former+h_voice_coil/2-h_top_plate/2-h_back-h_waveguide'});
model.geom('geom1').run('r1');
model.geom('geom1').create('r2', 'Rectangle');
model.geom('geom1').feature('r2').set('size', {'th_voice_coil+2*air_gap' '1'});
model.geom('geom1').feature('r2').setIndex('size', 'h_voice_coil', 1);
model.geom('geom1').feature('r2').set('pos', {'d_voice_coil/2-air_gap' '0'});
model.geom('geom1').feature('r2').setIndex('pos', '-h_former-h_waveguide', 1);
model.geom('geom1').feature('r2').setIndex('layername', 'Layer 1', 0);
model.geom('geom1').feature('r2').setIndex('layer', 'air_gap', 0);
model.geom('geom1').feature('r2').set('layerleft', true);
model.geom('geom1').feature('r2').set('layerright', true);
model.geom('geom1').feature('r2').set('layerbottom', false);
model.geom('geom1').run('r2');
model.geom('geom1').create('pol1', 'Polygon');
model.geom('geom1').feature('pol1').set('source', 'table');
model.geom('geom1').feature('pol1').set('type', 'open');
model.geom('geom1').feature('pol1').setIndex('table', 0, 0, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2+h_top_plate/2-h_waveguide', 0, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_voice_coil/2-air_gap', 1, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2+h_top_plate/2-h_waveguide', 1, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_voice_coil/2-air_gap', 2, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2-h_top_plate/2-h_back-h_waveguide', 2, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_magnet/2', 3, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2-h_top_plate/2-h_back-h_waveguide', 3, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_magnet/2', 4, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2-h_top_plate/2-h_waveguide', 4, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_voice_coil/2+th_voice_coil+air_gap', 5, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2-h_top_plate/2-h_waveguide', 5, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_voice_coil/2+th_voice_coil+air_gap', 6, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2+h_top_plate/2-h_waveguide', 6, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp', 7, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_former+h_voice_coil/2+h_top_plate/2-h_waveguide', 7, 1);
model.geom('geom1').feature('pol1').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp', 8, 0);
model.geom('geom1').feature('pol1').setIndex('table', '-h_waveguide', 8, 1);
model.geom('geom1').run('pol1');
model.geom('geom1').create('ic1', 'InterpolationCurve');
model.geom('geom1').feature('ic1').setIndex('table', 0, 0, 0);
model.geom('geom1').feature('ic1').setIndex('table', 'd1-h_waveguide', 0, 1);
model.geom('geom1').feature('ic1').setIndex('table', '(d_voice_coil/2)*1/5', 1, 0);
model.geom('geom1').feature('ic1').setIndex('table', 'd2-h_waveguide', 1, 1);
model.geom('geom1').feature('ic1').setIndex('table', '(d_voice_coil/2)*2/5', 2, 0);
model.geom('geom1').feature('ic1').setIndex('table', 'd3-h_waveguide', 2, 1);
model.geom('geom1').feature('ic1').setIndex('table', '(d_voice_coil/2)*3/5', 3, 0);
model.geom('geom1').feature('ic1').setIndex('table', 'd4-h_waveguide', 3, 1);
model.geom('geom1').feature('ic1').setIndex('table', '(d_voice_coil/2)*4/5', 4, 0);
model.geom('geom1').feature('ic1').setIndex('table', 'd5-h_waveguide', 4, 1);
model.geom('geom1').feature('ic1').setIndex('table', '(d_voice_coil/2)*5/5', 5, 0);
model.geom('geom1').feature('ic1').setIndex('table', '-h_waveguide', 5, 1);
model.geom('geom1').feature('ic1').set('startcond', 'tangent');
model.geom('geom1').feature('ic1').set('starttang', {'cos(alpha1)' '0'});
model.geom('geom1').feature('ic1').setIndex('starttang', '-sin(alpha1)', 1);
model.geom('geom1').feature('ic1').set('endcond', 'tangent');
model.geom('geom1').feature('ic1').set('endtang', {'cos(alpha2)' '0'});
model.geom('geom1').feature('ic1').setIndex('endtang', '-sin(alpha2)', 1);
model.geom('geom1').run('ic1');
model.geom('geom1').create('ic2', 'InterpolationCurve');
model.geom('geom1').feature('ic2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp', 0, 0);
model.geom('geom1').feature('ic2').setIndex('table', '-h_waveguide', 0, 1);
model.geom('geom1').feature('ic2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))*1/5', 1, 0);
model.geom('geom1').feature('ic2').setIndex('table', 'w1-h_waveguide', 1, 1);
model.geom('geom1').feature('ic2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))*2/5', 2, 0);
model.geom('geom1').feature('ic2').setIndex('table', 'w2-h_waveguide', 2, 1);
model.geom('geom1').feature('ic2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))*3/5', 3, 0);
model.geom('geom1').feature('ic2').setIndex('table', 'w3-h_waveguide', 3, 1);
model.geom('geom1').feature('ic2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))*4/5', 4, 0);
model.geom('geom1').feature('ic2').setIndex('table', 'w4-h_waveguide', 4, 1);
model.geom('geom1').feature('ic2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))*5/5', 5, 0);
model.geom('geom1').feature('ic2').setIndex('table', 0, 5, 1);
model.geom('geom1').feature('ic2').set('startcond', 'tangent');
model.geom('geom1').feature('ic2').set('starttang', {'cos(beta1)' 'sin(beta1)'});
model.geom('geom1').feature('ic2').set('endcond', 'tangent');
model.geom('geom1').feature('ic2').set('endtang', {'cos(beta2)' 'sin(beta2)'});
model.geom('geom1').run('ic2');
model.geom('geom1').create('ls1', 'LineSegment');
model.geom('geom1').feature('ls1').label('Former');
model.geom('geom1').feature('ls1').selection('vertex1').set('ic1', 2);
model.geom('geom1').feature('ls1').selection('vertex2').set('r2', 3);
model.geom('geom1').feature('ls1').set('selresult', true);
model.geom('geom1').run('ls1');
model.geom('geom1').create('ls2', 'LineSegment');
model.geom('geom1').feature('ls2').selection('vertex1').set('ic2', 2);
model.geom('geom1').feature('ls2').set('specify2', 'coord');
model.geom('geom1').feature('ls2').set('coord2', {'r_model+th_pml' '0'});
model.geom('geom1').run('ls2');
model.geom('geom1').create('ca1', 'CircularArc');
model.geom('geom1').feature('ca1').set('center', {'d_voice_coil/2+r1_susp' '0'});
model.geom('geom1').feature('ca1').setIndex('center', '(-h_former+h_voice_coil/2+h_top_plate/2)*2/3-h_waveguide', 1);
model.geom('geom1').feature('ca1').set('r', 'r1_susp');
model.geom('geom1').feature('ca1').set('angle2', 180);
model.geom('geom1').run('ca1');
model.geom('geom1').create('ca2', 'CircularArc');
model.geom('geom1').feature('ca2').set('center', {'d_voice_coil/2+2*r1_susp+r2_susp' '0'});
model.geom('geom1').feature('ca2').setIndex('center', '(-h_former+h_voice_coil/2+h_top_plate/2)*2/3-h_waveguide', 1);
model.geom('geom1').feature('ca2').set('r', 'r2_susp');
model.geom('geom1').feature('ca2').set('angle1', -180);
model.geom('geom1').feature('ca2').set('angle2', 0);
model.geom('geom1').run('ca2');
model.geom('geom1').create('ca3', 'CircularArc');
model.geom('geom1').feature('ca3').set('center', {'d_voice_coil/2+3*r1_susp+2*r2_susp' '0'});
model.geom('geom1').feature('ca3').setIndex('center', '(-h_former+h_voice_coil/2+h_top_plate/2)*2/3-h_waveguide', 1);
model.geom('geom1').feature('ca3').set('r', 'r1_susp');
model.geom('geom1').feature('ca3').set('angle2', 180);
model.geom('geom1').run('ca3');
model.geom('geom1').create('mir1', 'Mirror');
model.geom('geom1').feature('mir1').selection('input').set({'ca1' 'ca2' 'ca3'});
model.geom('geom1').feature('mir1').set('keep', true);
model.geom('geom1').feature('mir1').set('pos', {'0' '(-h_former+h_voice_coil/2+h_top_plate/2)/2 -h_waveguide'});
model.geom('geom1').feature('mir1').set('axis', [0 4]);
model.geom('geom1').run('mir1');
model.geom('geom1').create('pol2', 'Polygon');
model.geom('geom1').feature('pol2').set('source', 'table');
model.geom('geom1').feature('pol2').set('type', 'open');
model.geom('geom1').feature('pol2').setIndex('table', 0, 0, 0);
model.geom('geom1').feature('pol2').setIndex('table', 'r_model/4', 0, 1);
model.geom('geom1').feature('pol2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))', 1, 0);
model.geom('geom1').feature('pol2').setIndex('table', 'r_model/4', 1, 1);
model.geom('geom1').feature('pol2').setIndex('table', 'd_voice_coil/2+4*r1_susp+2*r2_susp+(d_waveguide/2-(d_voice_coil/2+4*r1_susp+2*r2_susp))', 2, 0);
model.geom('geom1').feature('pol2').setIndex('table', 0, 2, 1);
model.geom('geom1').run('pol2');
model.geom('geom1').create('r3', 'Rectangle');
model.geom('geom1').feature('r3').label('Porous Domain');
model.geom('geom1').feature('r3').set('size', {'d_porous/2' 'h_porous'});
model.geom('geom1').feature('r3').set('pos', {'0' '-h_former+h_voice_coil/2+h_top_plate/2-h_waveguide'});
model.geom('geom1').feature('r3').set('selresult', true);
model.geom('geom1').run('r3');
model.geom('geom1').create('uni1', 'Union');
model.geom('geom1').feature('uni1').selection('input').set({'c1' 'ca1' 'ca2' 'ca3' 'ic1' 'ic2' 'ls1' 'ls2' 'mir1' 'pol1'  ...
'pol2' 'r1' 'r2' 'r3'});
model.geom('geom1').run('uni1');
model.geom('geom1').create('del1', 'Delete');
model.geom('geom1').feature('del1').selection('input').init(2);
model.geom('geom1').feature('del1').selection('input').set('uni1', [1 8 15]);
model.geom('geom1').run('del1');
model.geom('geom1').run('fin');
model.geom('geom1').create('ige1', 'IgnoreEdges');
model.geom('geom1').feature('ige1').selection('input').set('fin', 7);
model.geom('geom1').run('ige1');
model.geom('geom1').create('sel1', 'ExplicitSelection');
model.geom('geom1').feature('sel1').label('PML Domains');
model.geom('geom1').feature('sel1').selection('selection').set('ige1', 5);
model.geom('geom1').run('sel1');
model.geom('geom1').create('sel2', 'ExplicitSelection');
model.geom('geom1').feature('sel2').label('Voice Coil');
model.geom('geom1').feature('sel2').selection('selection').set('ige1', 8);
model.geom('geom1').run('sel2');
model.geom('geom1').create('comsel1', 'ComplementSelection');
model.geom('geom1').feature('comsel1').set('input', {'sel2'});
model.geom('geom1').feature('comsel1').label('Air Domains');
model.geom('geom1').run('comsel1');
model.geom('geom1').create('sel3', 'ExplicitSelection');
model.geom('geom1').feature('sel3').label('Narrow Regions');
model.geom('geom1').feature('sel3').selection('selection').set('ige1', [7 11]);
model.geom('geom1').run('sel3');
model.geom('geom1').create('sel4', 'ExplicitSelection');
model.geom('geom1').feature('sel4').label('Visualization Domains');
model.geom('geom1').feature('sel4').selection('selection').set('ige1', [1 2 3 6 7 9 10 11]);
model.geom('geom1').run('sel4');
model.geom('geom1').create('sel5', 'ExplicitSelection');
model.geom('geom1').feature('sel5').label('Exterior Field');
model.geom('geom1').feature('sel5').selection('selection').init(1);
model.geom('geom1').feature('sel5').selection('selection').set('ige1', 38);
model.geom('geom1').run('sel5');
model.geom('geom1').create('sel6', 'ExplicitSelection');
model.geom('geom1').feature('sel6').label('Dome');
model.geom('geom1').feature('sel6').selection('selection').init(1);
model.geom('geom1').feature('sel6').selection('selection').set('ige1', 40);
model.geom('geom1').run('sel6');
model.geom('geom1').create('sel7', 'ExplicitSelection');
model.geom('geom1').feature('sel7').label('Symmetry/Roller Boundaries');
model.geom('geom1').feature('sel7').selection('selection').init(1);
model.geom('geom1').feature('sel7').selection('selection').set('ige1', [3 5]);
model.geom('geom1').run('sel7');
model.geom('geom1').create('sel8', 'ExplicitSelection');
model.geom('geom1').feature('sel8').label('Suspension');
model.geom('geom1').feature('sel8').selection('selection').init(1);
model.geom('geom1').feature('sel8').selection('selection').set('ige1', [41 42 43 44 45 46]);
model.geom('geom1').run('sel8');
model.geom('geom1').create('sel9', 'ExplicitSelection');
model.geom('geom1').feature('sel9').label('Revolution Boundaries');
model.geom('geom1').feature('sel9').selection('selection').init(1);
model.geom('geom1').feature('sel9').selection('selection').set('ige1', [2 4 9 10 11 12 13 15 17 18 19 20 21 22 23 26 27 28 29 30 31 32 33 34 40 41 42 43 44 45 46 47]);
model.geom('geom1').run('sel9');
model.geom('geom1').create('unisel1', 'UnionSelection');
model.geom('geom1').feature('unisel1').label('Shell Boundaries');
model.geom('geom1').feature('unisel1').set('entitydim', 1);
model.geom('geom1').feature('unisel1').set('input', {'ls1' 'sel6' 'sel8'});
model.geom('geom1').run('unisel1');
model.geom('geom1').create('sel10', 'ExplicitSelection');
model.geom('geom1').feature('sel10').label('Waveguide');
model.geom('geom1').feature('sel10').selection('selection').init(1);
model.geom('geom1').feature('sel10').selection('selection').set('ige1', 47);
model.geom('geom1').run('sel10');
model.geom('geom1').create('sel11', 'ExplicitSelection');
model.geom('geom1').feature('sel11').label('Fixed Points');
model.geom('geom1').feature('sel11').selection('selection').init(0);
model.geom('geom1').feature('sel11').selection('selection').set('ige1', [31 32]);

model.title([]);

model.description('');

model.label('tweeter_shape_optimization_geom_sequence.mph');

model.modelNode.label('Components');

out = model;
