function out = model
%
% capacitive_position_sensor_bem.m
%
% Model exported on May 26 2025, 21:24 by COMSOL 6.2.0.339.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/Applications/COMSOL62/Multiphysics/applications/ACDC_Module/Devices,_Capacitive');

model.modelNode.create('comp1', true);

model.geom.create('geom1', 3);
model.geom('geom1').model('comp1');

model.mesh.create('mesh1', 'geom1');

model.physics.create('esbe', 'ElectrostaticsBoundaryElements', 'geom1');
model.physics('esbe').model('comp1');

model.study.create('std1');
model.study('std1').create('stssw', 'StationarySourceSweep');
model.study('std1').feature('stssw').set('solnum', 'auto');
model.study('std1').feature('stssw').set('notsolnum', 'auto');
model.study('std1').feature('stssw').set('outputmap', {});
model.study('std1').feature('stssw').set('ngenAUX', '1');
model.study('std1').feature('stssw').set('goalngenAUX', '1');
model.study('std1').feature('stssw').set('ngenAUX', '1');
model.study('std1').feature('stssw').set('goalngenAUX', '1');
model.study('std1').feature('stssw').setSolveFor('/physics/esbe', true);

model.geom('geom1').create('blk1', 'Block');
model.geom('geom1').feature('blk1').set('size', {'11[cm]' '11[cm]' '1'});
model.geom('geom1').feature('blk1').setIndex('size', '1[cm]', 2);
model.geom('geom1').run('blk1');
model.geom('geom1').create('wp1', 'WorkPlane');
model.geom('geom1').feature('wp1').set('unite', true);
model.geom('geom1').feature('wp1').set('quickz', '5[mm]');
model.geom('geom1').feature('wp1').geom.create('r1', 'Rectangle');
model.geom('geom1').feature('wp1').geom.feature('r1').set('size', {'1[cm]' '11[cm]'});
model.geom('geom1').feature('wp1').geom.feature('r1').set('pos', {'1[cm]' '0'});
model.geom('geom1').feature('wp1').geom.run('r1');
model.geom('geom1').feature('wp1').geom.create('arr1', 'Array');
model.geom('geom1').feature('wp1').geom.feature('arr1').selection('input').set({'r1'});
model.geom('geom1').feature('wp1').geom.feature('arr1').set('fullsize', [5 1]);
model.geom('geom1').feature('wp1').geom.feature('arr1').set('displ', {'2[cm]' '0'});
model.geom('geom1').feature('wp1').geom.run('arr1');
model.geom('geom1').run('wp1');

model.view('view1').set('renderwireframe', true);

model.geom('geom1').run;

model.material.create('mat1', 'Common', 'comp1');
model.material('mat1').propertyGroup('def').func.create('eta', 'Piecewise');
model.material('mat1').propertyGroup('def').func.create('Cp', 'Piecewise');
model.material('mat1').propertyGroup('def').func.create('rho', 'Analytic');
model.material('mat1').propertyGroup('def').func.create('k', 'Piecewise');
model.material('mat1').propertyGroup('def').func.create('cs', 'Analytic');
model.material('mat1').propertyGroup('def').func.create('an1', 'Analytic');
model.material('mat1').propertyGroup('def').func.create('an2', 'Analytic');
model.material('mat1').propertyGroup.create('RefractiveIndex', 'Refractive index');
model.material('mat1').propertyGroup.create('NonlinearModel', 'Nonlinear model');
model.material('mat1').propertyGroup.create('idealGas', 'Ideal gas');
model.material('mat1').propertyGroup('idealGas').func.create('Cp', 'Piecewise');
model.material('mat1').label('Air');
model.material('mat1').set('family', 'air');
model.material('mat1').propertyGroup('def').func('eta').set('arg', 'T');
model.material('mat1').propertyGroup('def').func('eta').set('pieces', {'200.0' '1600.0' '-8.38278E-7+8.35717342E-8*T^1-7.69429583E-11*T^2+4.6437266E-14*T^3-1.06585607E-17*T^4'});
model.material('mat1').propertyGroup('def').func('eta').set('argunit', 'K');
model.material('mat1').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.material('mat1').propertyGroup('def').func('Cp').set('arg', 'T');
model.material('mat1').propertyGroup('def').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.material('mat1').propertyGroup('def').func('Cp').set('argunit', 'K');
model.material('mat1').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.material('mat1').propertyGroup('def').func('rho').set('expr', 'pA*0.02897/R_const[K*mol/J]/T');
model.material('mat1').propertyGroup('def').func('rho').set('args', {'pA' 'T'});
model.material('mat1').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.material('mat1').propertyGroup('def').func('rho').set('argunit', {'Pa' 'K'});
model.material('mat1').propertyGroup('def').func('rho').set('plotaxis', {'off' 'on'});
model.material('mat1').propertyGroup('def').func('rho').set('plotfixedvalue', {'101325' '273.15'});
model.material('mat1').propertyGroup('def').func('rho').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '293.15'});
model.material('mat1').propertyGroup('def').func('k').set('arg', 'T');
model.material('mat1').propertyGroup('def').func('k').set('pieces', {'200.0' '1600.0' '-0.00227583562+1.15480022E-4*T^1-7.90252856E-8*T^2+4.11702505E-11*T^3-7.43864331E-15*T^4'});
model.material('mat1').propertyGroup('def').func('k').set('argunit', 'K');
model.material('mat1').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.material('mat1').propertyGroup('def').func('cs').set('expr', 'sqrt(1.4*R_const[K*mol/J]/0.02897*T)');
model.material('mat1').propertyGroup('def').func('cs').set('args', {'T'});
model.material('mat1').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.material('mat1').propertyGroup('def').func('cs').set('argunit', {'K'});
model.material('mat1').propertyGroup('def').func('cs').set('plotfixedvalue', {'273.15'});
model.material('mat1').propertyGroup('def').func('cs').set('plotargs', {'T' '273.15' '373.15'});
model.material('mat1').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.material('mat1').propertyGroup('def').func('an1').set('expr', '-1/rho(pA,T)*d(rho(pA,T),T)');
model.material('mat1').propertyGroup('def').func('an1').set('args', {'pA' 'T'});
model.material('mat1').propertyGroup('def').func('an1').set('fununit', '1/K');
model.material('mat1').propertyGroup('def').func('an1').set('argunit', {'Pa' 'K'});
model.material('mat1').propertyGroup('def').func('an1').set('plotaxis', {'off' 'on'});
model.material('mat1').propertyGroup('def').func('an1').set('plotfixedvalue', {'101325' '273.15'});
model.material('mat1').propertyGroup('def').func('an1').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '373.15'});
model.material('mat1').propertyGroup('def').func('an2').set('funcname', 'muB');
model.material('mat1').propertyGroup('def').func('an2').set('expr', '0.6*eta(T)');
model.material('mat1').propertyGroup('def').func('an2').set('args', {'T'});
model.material('mat1').propertyGroup('def').func('an2').set('fununit', 'Pa*s');
model.material('mat1').propertyGroup('def').func('an2').set('argunit', {'K'});
model.material('mat1').propertyGroup('def').func('an2').set('plotfixedvalue', {'200'});
model.material('mat1').propertyGroup('def').func('an2').set('plotargs', {'T' '200' '1600'});
model.material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.material('mat1').propertyGroup('def').set('molarmass', '');
model.material('mat1').propertyGroup('def').set('bulkviscosity', '');
model.material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)'});
model.material('mat1').propertyGroup('def').set('molarmass', '0.02897[kg/mol]');
model.material('mat1').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.material('mat1').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.material('mat1').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.material('mat1').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.material('mat1').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.material('mat1').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.material('mat1').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.material('mat1').propertyGroup('def').set('density', 'rho(pA,T)');
model.material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.material('mat1').propertyGroup('def').set('soundspeed', 'cs(T)');
model.material('mat1').propertyGroup('def').addInput('temperature');
model.material('mat1').propertyGroup('def').addInput('pressure');
model.material('mat1').propertyGroup('RefractiveIndex').set('n', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.material('mat1').propertyGroup('NonlinearModel').set('BA', 'def.gamma-1');
model.material('mat1').propertyGroup('idealGas').func('Cp').label('Piecewise 2');
model.material('mat1').propertyGroup('idealGas').func('Cp').set('arg', 'T');
model.material('mat1').propertyGroup('idealGas').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.material('mat1').propertyGroup('idealGas').func('Cp').set('argunit', 'K');
model.material('mat1').propertyGroup('idealGas').func('Cp').set('fununit', 'J/(kg*K)');
model.material('mat1').propertyGroup('idealGas').set('Rs', 'R_const/Mn');
model.material('mat1').propertyGroup('idealGas').set('heatcapacity', 'Cp(T)');
model.material('mat1').propertyGroup('idealGas').set('ratioofspecificheat', '1.4');
model.material('mat1').propertyGroup('idealGas').set('molarmass', '0.02897');
model.material('mat1').propertyGroup('idealGas').addInput('temperature');
model.material('mat1').propertyGroup('idealGas').addInput('pressure');
model.material('mat1').materialType('nonSolid');
model.material.create('mat2', 'Common', 'comp1');
model.material('mat2').propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
model.material('mat2').label('Nylon');
model.material('mat2').set('family', 'custom');
model.material('mat2').set('customspecular', [0.7843137254901961 0.7843137254901961 0.7843137254901961]);
model.material('mat2').set('customdiffuse', [0.39215686274509803 0.39215686274509803 0.9803921568627451]);
model.material('mat2').set('customambient', [0.39215686274509803 0.39215686274509803 0.7843137254901961]);
model.material('mat2').set('noise', true);
model.material('mat2').set('lighting', 'phong');
model.material('mat2').set('shininess', 500);
model.material('mat2').propertyGroup('def').set('heatcapacity', '1700[J/(kg*K)]');
model.material('mat2').propertyGroup('def').set('relpermittivity', {'4' '0' '0' '0' '4' '0' '0' '0' '4'});
model.material('mat2').propertyGroup('def').set('thermalexpansioncoefficient', {'280e-6[1/K]' '0' '0' '0' '280e-6[1/K]' '0' '0' '0' '280e-6[1/K]'});
model.material('mat2').propertyGroup('def').set('density', '1150[kg/m^3]');
model.material('mat2').propertyGroup('def').set('thermalconductivity', {'0.26[W/(m*K)]' '0' '0' '0' '0.26[W/(m*K)]' '0' '0' '0' '0.26[W/(m*K)]'});
model.material('mat2').propertyGroup('Enu').set('E', '2[GPa]');
model.material('mat2').propertyGroup('Enu').set('nu', '0.4');
model.material('mat2').selection.set([1]);
model.material('mat1').selection.set([]);
model.material('mat1').selection.allVoids;

model.physics('esbe').create('ccn2', 'ChargeConservation', 3);
model.physics('esbe').feature('ccn2').selection.set([1]);
model.physics('esbe').create('gnd1', 'Ground', 2);
model.physics('esbe').feature('gnd1').selection.set([3]);
model.physics('esbe').create('term1', 'Terminal', 2);
model.physics('esbe').feature('term1').selection.set([6]);
model.physics('esbe').create('term2', 'Terminal', 2);
model.physics('esbe').feature('term2').selection.set([7]);
model.physics('esbe').create('term3', 'Terminal', 2);
model.physics('esbe').feature('term3').selection.set([8]);
model.physics('esbe').create('term4', 'Terminal', 2);
model.physics('esbe').feature('term4').selection.set([9]);
model.physics('esbe').create('term5', 'Terminal', 2);
model.physics('esbe').feature('term5').selection.set([10]);

model.mesh('mesh1').autoMeshSize(3);
model.mesh('mesh1').run;

model.physics('esbe').prop('ShapeProperty').set('shapeorder', 'p11');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stssw');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stssw');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').feature('p1').set('preusesol', 'no');
model.sol('sol1').feature('s1').feature('p1').set('pcontinuationmode', 'no');
model.sol('sol1').feature('s1').feature('p1').set('control', 'stssw');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'bicgstab');
model.sol('sol1').feature('s1').feature('i1').set('prefuntype', 'right');
model.sol('sol1').feature('s1').feature('i1').label('Suggested Iterative Solver (esbe)');
model.sol('sol1').feature('s1').feature('i1').create('dp1', 'DirectPreconditioner');
model.sol('sol1').feature('s1').feature('i1').feature('dp1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').create('i2', 'Iterative');
model.sol('sol1').feature('s1').feature('i2').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i2').set('prefuntype', 'right');
model.sol('sol1').feature('s1').feature('i2').label('GMRES Iterative Solver (esbe)');
model.sol('sol1').feature('s1').feature('i2').create('dp1', 'DirectPreconditioner');
model.sol('sol1').feature('s1').feature('i2').feature('dp1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'dense');
model.sol('sol1').feature('s1').feature('d1').label('Suggested Direct Solver (esbe)');
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'i1');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');
model.sol('sol1').feature('s1').feature('dDef').active(true);
model.sol('sol1').runAll;

model.result.dataset.create('grid1', 'Grid3D');
model.result.dataset('grid1').set('source', 'data');
model.result.dataset('grid1').set('data', 'dset1');
model.result.dataset('grid1').set('par1', 'x');
model.result.dataset('grid1').set('par2', 'y');
model.result.dataset('grid1').set('par3', 'z');
model.result.dataset('grid1').set('parmin1', -0.11);
model.result.dataset('grid1').set('parmax1', 0.22);
model.result.dataset('grid1').set('parmin2', -0.11000000000000004);
model.result.dataset('grid1').set('parmax2', 0.22000000000000008);
model.result.dataset('grid1').set('parmin3', -0.01);
model.result.dataset('grid1').set('parmax3', 0.02);
model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').set('data', 'grid1');
model.result('pg1').setIndex('looplevel', 5, 0);
model.result('pg1').create('mslc1', 'Multislice');
model.result('pg1').feature('mslc1').set('expr', {'esbe.V'});
model.result('pg1').feature('mslc1').set('solutionparams', 'parent');
model.result('pg1').feature('mslc1').set('colortable', 'Dipole');
model.result('pg1').feature('mslc1').set('smooth', 'internal');
model.result('pg1').label('Electric Potential (esbe)');
model.result('pg1').set('frametype', 'spatial');
model.result('pg1').set('showlegendsmaxmin', true);
model.result('pg1').create('strmsl1', 'StreamlineMultislice');
model.result('pg1').feature('strmsl1').set('expr', {'esbe.Ex' 'esbe.Ey' 'esbe.Ez'});
model.result('pg1').feature('strmsl1').set('solutionparams', 'parent');
model.result('pg1').feature('strmsl1').set('titletype', 'none');
model.result('pg1').feature('strmsl1').set('posmethod', 'uniform');
model.result('pg1').feature('strmsl1').set('udist', '0.02');
model.result('pg1').feature('strmsl1').set('smooth', 'internal');
model.result('pg1').feature('strmsl1').set('maxlen', '0.4');
model.result('pg1').feature('strmsl1').set('inheritplot', 'mslc1');
model.result('pg1').feature('strmsl1').set('inheritcolor', false);
model.result('pg1').feature('strmsl1').create('col1', 'Color');
model.result('pg1').feature('strmsl1').feature('col1').set('expr', {'esbe.V'});
model.result('pg1').feature('strmsl1').feature('col1').set('colorlegend', false);
model.result('pg1').feature('strmsl1').feature('col1').set('colortable', 'DipoleDark');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr', {'esbe.V'});
model.result('pg1').feature('surf1').set('data', 'dset1');
model.result('pg1').feature('surf1').set('solutionparams', 'parent');
model.result('pg1').feature('surf1').set('titletype', 'none');
model.result('pg1').feature('surf1').set('colortable', 'Dipole');
model.result('pg1').feature('surf1').set('smooth', 'material');
model.result('pg1').feature('surf1').set('inheritplot', 'mslc1');
model.result('pg1').create('line1', 'Line');
model.result('pg1').feature('line1').set('expr', {'1'});
model.result('pg1').feature('line1').set('data', 'dset1');
model.result('pg1').feature('line1').set('titletype', 'none');
model.result('pg1').feature('line1').set('coloring', 'uniform');
model.result('pg1').feature('line1').set('color', 'black');
model.result('pg1').feature('line1').set('solutionparams', 'parent');
model.result.create('pg2', 'PlotGroup3D');
model.result('pg2').set('data', 'grid1');
model.result('pg2').setIndex('looplevel', 5, 0);
model.result('pg2').create('mslc1', 'Multislice');
model.result('pg2').feature('mslc1').set('expr', {'esbe.normE'});
model.result('pg2').feature('mslc1').set('solutionparams', 'parent');
model.result('pg2').feature('mslc1').set('colortable', 'Prism');
model.result('pg2').feature('mslc1').set('colortabletrans', 'nonlinear');
model.result('pg2').feature('mslc1').set('colorcalibration', '-0.8');
model.result('pg2').feature('mslc1').set('smooth', 'internal');
model.result('pg2').label('Electric Field Norm (esbe)');
model.result('pg2').set('frametype', 'spatial');
model.result('pg2').set('showlegendsmaxmin', true);
model.result('pg2').create('strmsl1', 'StreamlineMultislice');
model.result('pg2').feature('strmsl1').set('expr', {'esbe.Ex' 'esbe.Ey' 'esbe.Ez'});
model.result('pg2').feature('strmsl1').set('solutionparams', 'parent');
model.result('pg2').feature('strmsl1').set('titletype', 'none');
model.result('pg2').feature('strmsl1').set('posmethod', 'uniform');
model.result('pg2').feature('strmsl1').set('udist', '0.02');
model.result('pg2').feature('strmsl1').set('smooth', 'internal');
model.result('pg2').feature('strmsl1').set('maxlen', '0.4');
model.result('pg2').feature('strmsl1').set('inheritplot', 'mslc1');
model.result('pg2').feature('strmsl1').set('inheritcolor', false);
model.result('pg2').feature('strmsl1').create('col1', 'Color');
model.result('pg2').feature('strmsl1').feature('col1').set('expr', {'esbe.normE'});
model.result('pg2').feature('strmsl1').feature('col1').set('colorlegend', false);
model.result('pg2').feature('strmsl1').feature('col1').set('colortable', 'PrismDark');
model.result('pg2').feature('strmsl1').feature('col1').set('colortabletrans', 'nonlinear');
model.result('pg2').feature('strmsl1').feature('col1').set('colorcalibration', '-0.8');
model.result('pg2').create('line1', 'Line');
model.result('pg2').feature('line1').set('expr', {'1'});
model.result('pg2').feature('line1').set('data', 'dset1');
model.result('pg2').feature('line1').set('titletype', 'none');
model.result('pg2').feature('line1').set('coloring', 'uniform');
model.result('pg2').feature('line1').set('color', 'black');
model.result('pg2').feature('line1').set('solutionparams', 'parent');
model.result.evaluationGroup.create('eg1', 'EvaluationGroup');
model.result.evaluationGroup('eg1').set('data', 'dset1');
model.result.evaluationGroup('eg1').label(' (esbe)');
model.result.evaluationGroup('eg1').label('Inverse Maxwell capacitance (dset1, esbe)');
model.result.evaluationGroup('eg1').create('gmev1', 'EvalGlobalMatrix');
model.result.evaluationGroup('eg1').feature('gmev1').label('Inverse Maxwell capacitance (dset1, esbe)');
model.result.evaluationGroup('eg1').feature('gmev1').set('expr', 'root.comp1.esbe.Cinv');
model.result.evaluationGroup('eg1').feature('gmev1').set('outerdataseries', 'none');
model.result.evaluationGroup('eg1').feature('gmev1').set('dataseries', 'sum');

model.nodeGroup.create('grp1', 'Results');
model.nodeGroup('grp1').label('Lumped Parameters (dset1, esbe)');
model.nodeGroup('grp1').set('type', 'evaluationgroup');
model.nodeGroup('grp1').add('evaluationgroup', 'eg1');

model.result.evaluationGroup('eg1').run;
model.result.evaluationGroup.create('eg2', 'EvaluationGroup');
model.result.evaluationGroup('eg2').set('data', 'dset1');
model.result.evaluationGroup('eg2').label(' (esbe)');
model.result.evaluationGroup('eg2').label('Maxwell capacitance (dset1, esbe)');
model.result.evaluationGroup('eg2').create('gmev1', 'EvalGlobalMatrix');
model.result.evaluationGroup('eg2').feature('gmev1').label('Maxwell capacitance (dset1, esbe)');
model.result.evaluationGroup('eg2').feature('gmev1').set('expr', 'root.comp1.esbe.Cinv');
model.result.evaluationGroup('eg2').feature('gmev1').set('outerdataseries', 'none');
model.result.evaluationGroup('eg2').feature('gmev1').set('dataseries', 'sum');
model.result.evaluationGroup('eg2').feature('gmev1').set('trans', 'inverse');

model.nodeGroup('grp1').add('evaluationgroup', 'eg2');

model.result.evaluationGroup('eg2').run;
model.result.evaluationGroup.create('eg3', 'EvaluationGroup');
model.result.evaluationGroup('eg3').set('data', 'dset1');
model.result.evaluationGroup('eg3').label(' (esbe)');
model.result.evaluationGroup('eg3').label('Mutual capacitance (dset1, esbe)');
model.result.evaluationGroup('eg3').create('gmev1', 'EvalGlobalMatrix');
model.result.evaluationGroup('eg3').feature('gmev1').label('Mutual capacitance (dset1, esbe)');
model.result.evaluationGroup('eg3').feature('gmev1').set('expr', 'root.comp1.esbe.Cinv');
model.result.evaluationGroup('eg3').feature('gmev1').set('outerdataseries', 'none');
model.result.evaluationGroup('eg3').feature('gmev1').set('dataseries', 'sum');
model.result.evaluationGroup('eg3').feature('gmev1').set('trans', 'invmaxwellmutual');

model.nodeGroup('grp1').add('evaluationgroup', 'eg3');

model.result.evaluationGroup('eg3').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('strmsl1').active(false);
model.result('pg1').run;
model.result('pg1').feature('mslc1').set('xnumber', '0');
model.result('pg1').feature('mslc1').set('znumber', '0');
model.result('pg1').run;
model.result.evaluationGroup('eg2').feature('gmev1').set('unit', '1/pF');
model.result.evaluationGroup('eg3').feature('gmev1').set('unit', '1/pF');
model.result.evaluationGroup('eg1').run;
model.result.evaluationGroup('eg2').run;
model.result.evaluationGroup('eg3').run;
model.result.create('pg3', 'PlotGroup2D');
model.result('pg3').set('data', 'none');
model.result('pg3').create('tbls1', 'TableSurface');
model.result('pg3').feature('tbls1').set('source', 'evaluationgroup');
model.result('pg3').feature('tbls1').set('evaluationgroup', 'eg3');
model.result('pg3').run;
model.result('pg3').feature('tbls1').set('dataformat', 'cells');
model.result('pg3').feature('tbls1').set('function', 'discrete');
model.result('pg3').run;
model.result('pg3').set('titletype', 'manual');
model.result('pg3').set('title', 'Mutual capacitance matrix [pF]');
model.result('pg3').run;

model.param.set('L', '2[cm]');
model.param.descr('L', 'Displacement');

model.geom('geom1').create('blk2', 'Block');
model.geom('geom1').feature('blk2').set('type', 'surface');
model.geom('geom1').feature('blk2').set('size', {'25[cm]' '5[cm]' '1'});
model.geom('geom1').feature('blk2').setIndex('size', '8[cm]', 2);
model.geom('geom1').feature('blk2').set('pos', {'-35[cm]' '3[cm]' '0'});
model.geom('geom1').feature('blk2').setIndex('pos', '2[cm]', 2);
model.geom('geom1').runPre('fin');
model.geom('geom1').feature('blk2').set('pos', {'-35[cm]+10[cm]' '3[cm]' '2[cm]'});
model.geom('geom1').runPre('fin');
model.geom('geom1').feature('blk2').set('pos', {'-35[cm]' '3[cm]' '2[cm]'});
model.geom('geom1').runPre('fin');

model.common.create('pres1', 'PrescribedDeformationDeformedGeometry', 'comp1');
model.common('pres1').selection.all;

model.geom('geom1').run;

model.common('pres1').selection.geom('geom1', 2);
model.common('pres1').selection.set([1 2 3 4 5 6]);
model.common('pres1').set('prescribedDeformation', {'L' '0' '0'});

model.physics('esbe').create('fp1', 'FloatingPotential', 2);
model.physics('esbe').feature('fp1').selection.set([1 2 3 4 5 6]);
model.physics('esbe').selection.set([0 1]);

model.mesh('mesh1').autoMeshSize(1);
model.mesh('mesh1').run;

model.study('std1').create('param', 'Parametric');
model.study('std1').feature('param').setIndex('pname', 'L', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', 'm', 0);
model.study('std1').feature('param').setIndex('pname', 'L', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', 'm', 0);
model.study('std1').feature('param').setIndex('plistarr', 'range(2,2,28)', 0);
model.study('std1').feature('param').setIndex('punit', 'cm', 0);

model.batch.create('p1', 'Parametric');
model.batch('p1').study('std1');
model.batch('p1').create('so1', 'Solutionseq');
model.batch('p1').feature('so1').set('seq', 'sol1');
model.batch('p1').feature('so1').set('store', 'on');
model.batch('p1').feature('so1').set('clear', 'on');
model.batch('p1').feature('so1').set('psol', 'none');
model.batch('p1').set('pname', {'L'});
model.batch('p1').set('plistarr', {'range(2,2,28)'});
model.batch('p1').set('sweeptype', 'sparse');
model.batch('p1').set('probesel', 'all');
model.batch('p1').set('probes', {});
model.batch('p1').set('plot', 'off');
model.batch('p1').set('err', 'on');
model.batch('p1').attach('std1');
model.batch('p1').set('control', 'param');

model.sol.create('sol2');
model.sol('sol2').study('std1');
model.sol('sol2').label('Parametric Solutions 1');

model.batch('p1').feature('so1').set('psol', 'sol2');
model.batch('p1').run('compute');

model.result.dataset.create('grid2', 'Grid3D');
model.result.dataset('grid2').set('source', 'data');
model.result.dataset('grid2').set('data', 'dset2');
model.result.dataset('grid2').set('par1', 'x');
model.result.dataset('grid2').set('par2', 'y');
model.result.dataset('grid2').set('par3', 'z');
model.result.dataset('grid2').set('parmin1', -0.8100000000000002);
model.result.dataset('grid2').set('parmax1', 0.5700000000000001);
model.result.dataset('grid2').set('parmin2', -0.11000000000000001);
model.result.dataset('grid2').set('parmax2', 0.22000000000000003);
model.result.dataset('grid2').set('parmin3', -0.1);
model.result.dataset('grid2').set('parmax3', 0.2);
model.result.create('pg4', 'PlotGroup3D');
model.result('pg4').set('data', 'grid2');
model.result('pg4').setIndex('looplevel', 5, 0);
model.result('pg4').setIndex('looplevel', 14, 1);
model.result('pg4').create('mslc1', 'Multislice');
model.result('pg4').feature('mslc1').set('expr', {'esbe.V'});
model.result('pg4').feature('mslc1').set('solutionparams', 'parent');
model.result('pg4').feature('mslc1').set('colortable', 'Dipole');
model.result('pg4').feature('mslc1').set('smooth', 'internal');
model.result('pg4').label('Electric Potential (esbe) 1');
model.result('pg4').set('frametype', 'spatial');
model.result('pg4').set('showlegendsmaxmin', true);
model.result('pg4').create('strmsl1', 'StreamlineMultislice');
model.result('pg4').feature('strmsl1').set('expr', {'esbe.Ex' 'esbe.Ey' 'esbe.Ez'});
model.result('pg4').feature('strmsl1').set('solutionparams', 'parent');
model.result('pg4').feature('strmsl1').set('titletype', 'none');
model.result('pg4').feature('strmsl1').set('posmethod', 'uniform');
model.result('pg4').feature('strmsl1').set('udist', '0.02');
model.result('pg4').feature('strmsl1').set('smooth', 'internal');
model.result('pg4').feature('strmsl1').set('maxlen', '0.4');
model.result('pg4').feature('strmsl1').set('inheritplot', 'mslc1');
model.result('pg4').feature('strmsl1').set('inheritcolor', false);
model.result('pg4').feature('strmsl1').create('col1', 'Color');
model.result('pg4').feature('strmsl1').feature('col1').set('expr', {'esbe.V'});
model.result('pg4').feature('strmsl1').feature('col1').set('colorlegend', false);
model.result('pg4').feature('strmsl1').feature('col1').set('colortable', 'DipoleDark');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('expr', {'esbe.V'});
model.result('pg4').feature('surf1').set('data', 'dset2');
model.result('pg4').feature('surf1').set('solutionparams', 'parent');
model.result('pg4').feature('surf1').set('titletype', 'none');
model.result('pg4').feature('surf1').set('colortable', 'Dipole');
model.result('pg4').feature('surf1').set('smooth', 'material');
model.result('pg4').feature('surf1').set('inheritplot', 'mslc1');
model.result('pg4').create('line1', 'Line');
model.result('pg4').feature('line1').set('expr', {'1'});
model.result('pg4').feature('line1').set('data', 'dset2');
model.result('pg4').feature('line1').set('titletype', 'none');
model.result('pg4').feature('line1').set('coloring', 'uniform');
model.result('pg4').feature('line1').set('color', 'black');
model.result('pg4').feature('line1').set('solutionparams', 'parent');
model.result.create('pg5', 'PlotGroup3D');
model.result('pg5').set('data', 'grid2');
model.result('pg5').setIndex('looplevel', 5, 0);
model.result('pg5').setIndex('looplevel', 14, 1);
model.result('pg5').create('mslc1', 'Multislice');
model.result('pg5').feature('mslc1').set('expr', {'esbe.normE'});
model.result('pg5').feature('mslc1').set('solutionparams', 'parent');
model.result('pg5').feature('mslc1').set('colortable', 'Prism');
model.result('pg5').feature('mslc1').set('colortabletrans', 'nonlinear');
model.result('pg5').feature('mslc1').set('colorcalibration', '-0.8');
model.result('pg5').feature('mslc1').set('smooth', 'internal');
model.result('pg5').label('Electric Field Norm (esbe) 1');
model.result('pg5').set('frametype', 'spatial');
model.result('pg5').set('showlegendsmaxmin', true);
model.result('pg5').create('strmsl1', 'StreamlineMultislice');
model.result('pg5').feature('strmsl1').set('expr', {'esbe.Ex' 'esbe.Ey' 'esbe.Ez'});
model.result('pg5').feature('strmsl1').set('solutionparams', 'parent');
model.result('pg5').feature('strmsl1').set('titletype', 'none');
model.result('pg5').feature('strmsl1').set('posmethod', 'uniform');
model.result('pg5').feature('strmsl1').set('udist', '0.02');
model.result('pg5').feature('strmsl1').set('smooth', 'internal');
model.result('pg5').feature('strmsl1').set('maxlen', '0.4');
model.result('pg5').feature('strmsl1').set('inheritplot', 'mslc1');
model.result('pg5').feature('strmsl1').set('inheritcolor', false);
model.result('pg5').feature('strmsl1').create('col1', 'Color');
model.result('pg5').feature('strmsl1').feature('col1').set('expr', {'esbe.normE'});
model.result('pg5').feature('strmsl1').feature('col1').set('colorlegend', false);
model.result('pg5').feature('strmsl1').feature('col1').set('colortable', 'PrismDark');
model.result('pg5').feature('strmsl1').feature('col1').set('colortabletrans', 'nonlinear');
model.result('pg5').feature('strmsl1').feature('col1').set('colorcalibration', '-0.8');
model.result('pg5').create('line1', 'Line');
model.result('pg5').feature('line1').set('expr', {'1'});
model.result('pg5').feature('line1').set('data', 'dset2');
model.result('pg5').feature('line1').set('titletype', 'none');
model.result('pg5').feature('line1').set('coloring', 'uniform');
model.result('pg5').feature('line1').set('color', 'black');
model.result('pg5').feature('line1').set('solutionparams', 'parent');
model.result.evaluationGroup.create('eg4', 'EvaluationGroup');
model.result.evaluationGroup('eg4').set('data', 'dset2');
model.result.evaluationGroup('eg4').label(' (esbe)');
model.result.evaluationGroup('eg4').label('Inverse Maxwell capacitance (dset2, esbe)');
model.result.evaluationGroup('eg4').create('gmev1', 'EvalGlobalMatrix');
model.result.evaluationGroup('eg4').feature('gmev1').label('Inverse Maxwell capacitance (dset2, esbe)');
model.result.evaluationGroup('eg4').feature('gmev1').set('expr', 'root.comp1.esbe.Cinv');
model.result.evaluationGroup('eg4').feature('gmev1').set('outerdataseries', 'none');
model.result.evaluationGroup('eg4').feature('gmev1').set('dataseries', 'sum');

model.nodeGroup.create('grp2', 'Results');
model.nodeGroup('grp2').label('Lumped Parameters (dset2, esbe)');
model.nodeGroup('grp2').set('type', 'evaluationgroup');
model.nodeGroup('grp2').add('evaluationgroup', 'eg4');

model.result.evaluationGroup('eg4').setIndex('looplevelinput', 'last', 1);
model.result.evaluationGroup('eg4').run;
model.result.evaluationGroup.create('eg5', 'EvaluationGroup');
model.result.evaluationGroup('eg5').set('data', 'dset2');
model.result.evaluationGroup('eg5').label(' (esbe)');
model.result.evaluationGroup('eg5').label('Maxwell capacitance (dset2, esbe)');
model.result.evaluationGroup('eg5').create('gmev1', 'EvalGlobalMatrix');
model.result.evaluationGroup('eg5').feature('gmev1').label('Maxwell capacitance (dset2, esbe)');
model.result.evaluationGroup('eg5').feature('gmev1').set('expr', 'root.comp1.esbe.Cinv');
model.result.evaluationGroup('eg5').feature('gmev1').set('outerdataseries', 'none');
model.result.evaluationGroup('eg5').feature('gmev1').set('dataseries', 'sum');
model.result.evaluationGroup('eg5').feature('gmev1').set('trans', 'inverse');

model.nodeGroup('grp2').add('evaluationgroup', 'eg5');

model.result.evaluationGroup('eg5').setIndex('looplevelinput', 'last', 1);
model.result.evaluationGroup('eg5').run;
model.result.evaluationGroup.create('eg6', 'EvaluationGroup');
model.result.evaluationGroup('eg6').set('data', 'dset2');
model.result.evaluationGroup('eg6').label(' (esbe)');
model.result.evaluationGroup('eg6').label('Mutual capacitance (dset2, esbe)');
model.result.evaluationGroup('eg6').create('gmev1', 'EvalGlobalMatrix');
model.result.evaluationGroup('eg6').feature('gmev1').label('Mutual capacitance (dset2, esbe)');
model.result.evaluationGroup('eg6').feature('gmev1').set('expr', 'root.comp1.esbe.Cinv');
model.result.evaluationGroup('eg6').feature('gmev1').set('outerdataseries', 'none');
model.result.evaluationGroup('eg6').feature('gmev1').set('dataseries', 'sum');
model.result.evaluationGroup('eg6').feature('gmev1').set('trans', 'invmaxwellmutual');

model.nodeGroup('grp2').add('evaluationgroup', 'eg6');

model.result.evaluationGroup('eg6').setIndex('looplevelinput', 'last', 1);
model.result.evaluationGroup('eg6').run;
model.result.create('pg6', 'PlotGroup3D');
model.result('pg6').set('data', 'dset2');
model.result('pg6').setIndex('looplevel', 5, 0);
model.result('pg6').setIndex('looplevel', 14, 1);
model.result('pg6').label('Deformed Geometry');
model.result('pg6').create('mesh1', 'Mesh');
model.result('pg6').feature('mesh1').set('meshdomain', 'surface');
model.result('pg6').feature('mesh1').set('colortable', 'TrafficFlow');
model.result('pg6').feature('mesh1').set('colortabletrans', 'nonlinear');
model.result('pg6').feature('mesh1').set('nonlinearcolortablerev', true);
model.result('pg6').feature('mesh1').create('sel1', 'MeshSelection');
model.result('pg6').feature('mesh1').feature('sel1').selection.set([1 2 3 4 5 6]);
model.result('pg6').feature('mesh1').set('qualmeasure', 'custom');
model.result('pg6').feature('mesh1').set('qualexpr', 'comp1.material.relVol');
model.result('pg6').feature('mesh1').set('colorrangeunitinterval', false);
model.result('pg4').run;
model.result('pg4').run;
model.result('pg4').feature('surf1').active(false);
model.result('pg4').run;
model.result.dataset('grid2').set('parmin1', -0.2);
model.result.dataset('grid2').set('parmax1', 0.2);
model.result.dataset('grid2').set('res1', 100);
model.result('pg4').run;
model.result('pg4').feature('strmsl1').active(false);
model.result('pg4').run;
model.result('pg4').feature('mslc1').set('xnumber', '0');
model.result('pg4').feature('mslc1').set('znumber', '0');
model.result('pg4').run;
model.result('pg4').run;
model.result('pg4').setIndex('looplevel', 1, 1);
model.result('pg4').run;
model.result('pg4').run;
model.result('pg4').feature('mslc1').set('expr', 'log10(esbe.V)');
model.result('pg4').feature('mslc1').set('rangecoloractive', true);
model.result('pg4').feature('mslc1').set('rangecolormin', -4);
model.result('pg4').feature('mslc1').set('rangecolormax', 0);
model.result('pg4').run;
model.result('pg4').run;
model.result('pg4').setIndex('looplevel', 1, 0);
model.result('pg4').run;
model.result('pg4').setIndex('looplevel', 5, 1);
model.result('pg4').run;
model.result('pg4').setIndex('looplevel', 9, 1);
model.result('pg4').run;
model.result.create('pg7', 'PlotGroup1D');
model.result('pg7').run;
model.result('pg7').set('data', 'dset2');
model.result('pg7').setIndex('looplevelinput', 'first', 0);
model.result('pg7').set('titletype', 'manual');
model.result('pg7').set('title', 'Relative change of capacitance');
model.result('pg7').create('glob1', 'Global');
model.result('pg7').feature('glob1').set('markerpos', 'datapoints');
model.result('pg7').feature('glob1').set('linewidth', 'preference');
model.result('pg7').feature('glob1').setIndex('expr', 'with(1,esbe.Cinv11)/withsol(''sol2'',with(1,esbe.Cinv11),setval(L,0.02))', 0);
model.result('pg7').feature('glob1').setIndex('descr', 'Terminal 1', 0);
model.result('pg7').feature('glob1').setIndex('expr', 'with(5,esbe.Cinv55)/withsol(''sol2'',with(5,esbe.Cinv55),setval(L,0.02))', 1);
model.result('pg7').feature('glob1').setIndex('descr', 'Terminal 5', 1);
model.result('pg7').feature('glob1').setIndex('expr', 'with(5,esbe.Cinv55)/with(1,esbe.Cinv11)/withsol(''sol2'',with(5,esbe.Cinv55)/with(1,esbe.Cinv11),setval(L,0.02))', 2);
model.result('pg7').feature('glob1').setIndex('descr', 'Ratio of capacitances for terminal 1 vs. 5', 2);
model.result('pg7').feature('glob1').set('xdatasolnumtype', 'level2');
model.result('pg7').feature('glob1').set('legendmethod', 'manual');
model.result('pg7').feature('glob1').setIndex('legends', 'Change on terminal 1', 0);
model.result('pg7').feature('glob1').setIndex('legends', 'Change on terminal 5', 1);
model.result('pg7').feature('glob1').setIndex('legends', 'Relative change of 1 vs. 5', 2);
model.result('pg7').run;
model.result('pg4').run;
model.result('pg4').run;

model.title('Modeling a Capacitive Position Sensor Using BEM');

model.description(['This tutorial model explains how to extract lumped matrices by means of the Stationary Source Sweep study. The capacitance matrix of a five-terminal system is used to infer the position of a metallic object rather like real-world capacitive position sensors.' newline  newline 'The example illustrates the use of the boundary element method (BEM), which is supported by the Electrostatics, Boundary Elements interface.']);

model.mesh.clearMeshes;

model.sol('sol1').clearSolutionData;
model.sol('sol2').clearSolutionData;
model.sol('sol3').clearSolutionData;
model.sol('sol4').clearSolutionData;
model.sol('sol5').clearSolutionData;
model.sol('sol6').clearSolutionData;
model.sol('sol7').clearSolutionData;
model.sol('sol8').clearSolutionData;
model.sol('sol9').clearSolutionData;
model.sol('sol10').clearSolutionData;
model.sol('sol11').clearSolutionData;
model.sol('sol12').clearSolutionData;
model.sol('sol13').clearSolutionData;
model.sol('sol14').clearSolutionData;
model.sol('sol15').clearSolutionData;
model.sol('sol16').clearSolutionData;

model.label('capacitive_position_sensor_bem.mph');

model.modelNode.label('Components');

out = model;
